[project]
name = "24b-research-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bedrock-agentcore>=1.1.1",
    "boto3>=1.42.5",
    "strands-agents>=1.19.0",
]
